site_name: 學生計算機年會 | Students' Information Technology Conference
description: 以學生為本、由學生自發舉辦，SITCON 學生計算機年會不只是學生「學以致用、教學相長」的實際展現，更冀望所有對資訊有興趣的學生，能夠在年會裏齊聚一堂，彼此激盪、傳承、啟發。
analytics:
  enabled: true
  code: UA-34467841-1
